# Generated by Django 4.2.3 on 2023-08-03 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='itemCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='product',
            name='imagen',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.CreateModel(
            name='ShoppingCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.itemcar')),
            ],
        ),
        migrations.AddField(
            model_name='itemcar',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='categorias',
            field=models.ManyToManyField(to='almacen.categoria'),
        ),
    ]
