# Generated by Django 4.2.3 on 2023-08-02 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_categoria_remove_product_categoria_product_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categoria',
            new_name='categorias',
        ),
    ]
