# Generated by Django 4.2.2 on 2023-08-03 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_categoria_remove_product_categoria_product_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='itemCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='categoria',
            new_name='categorias',
        ),
        migrations.CreateModel(
            name='ShoppingCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.itemcar')),
            ],
        ),
        migrations.AddField(
            model_name='itemcar',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.product'),
        ),
    ]
