# Generated by Django 4.2.2 on 2023-08-03 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_delete_customuser'),
        ('almacen', '0003_itemcar_rename_categoria_product_categorias_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShoppingCar',
        ),
    ]
