# Generated by Django 4.2.2 on 2023-08-04 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0006_shoppingcar_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcar',
            name='user',
        ),
    ]
